<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit151986df9af9b8582943e4923407562a
{
    public static $prefixLengthsPsr4 = array (
        
        'P' => 
        array (
            'PHPSocketIO\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        
        'PHPSocketIO\\' => 
        array (
            0 => __DIR__ . '/..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit151986df9af9b8582943e4923407562a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit151986df9af9b8582943e4923407562a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
