<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit61840820867916a09bcb2cac8d4e7185
{
    public static $prefixLengthsPsr4 = array (
        
        'P' => 
        array (
            'PHPSocketIO\\' => 12,
        ),
        
    );

    public static $prefixDirsPsr4 = array (
        
        'PHPSocketIO\\' =>
        array (
            0 => __DIR__ . '/..' . '/workerman/phpsocket.io/src',
        ),
        
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit61840820867916a09bcb2cac8d4e7185::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit61840820867916a09bcb2cac8d4e7185::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
